"""empty message

Revision ID: 555695c86c1f
Revises: 
Create Date: 2024-02-27 10:34:56.792249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555695c86c1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('distance_from_earth', sa.Integer(), nullable=True),
    sa.Column('nearest_star', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planets_table'))
    )
    op.create_table('scientists_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scientists_table'))
    )
    op.create_table('missions_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('scientist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets_table.id'], name=op.f('fk_missions_table_planet_id_planets_table')),
    sa.ForeignKeyConstraint(['scientist_id'], ['scientists_table.id'], name=op.f('fk_missions_table_scientist_id_scientists_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions_table')
    op.drop_table('scientists_table')
    op.drop_table('planets_table')
    # ### end Alembic commands ###
